before_script:
  - git config --global http.proxy http://proxy-us.intel.com:911
  - git config --global https.proxy http://proxy-us.intel.com:911
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.devtools.intel.com".insteadOf "https://gitlab.devtools.intel.com"
  - export http_proxy=http://proxy-us.intel.com:911
  - export https_proxy=http://proxy-us.intel.com:911
  - export no_proxy=127.0.0.1,localhost,gitlab.devtools.intel.com

# the gta-unit-test is a container that remains alive across builds/tests.  clean up
# the gitlab url otherwise they accumulate and expire
after_script:
  - git config --global --unset url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.devtools.intel.com".insteadOf

stages:
  - build
  - test

build:gta:
  stage: build
  image: gta-devel
  tags:
    - gta
  script:
    - make
  artifacts:
    paths:
      - "out/tpmprovider.test"

test:
  stage: test
  image: gta-devel
  tags:
    - gta-unit-test
  script:
    - export CGO_CFLAGS_ALLOW="-f.*"
    - go test ./... -tags=unit_test -coverpkg=./... -coverprofile out/cover.out
    - go tool cover -func out/cover.out
    - go tool cover -html=out/cover.out -o out/cover.html
  artifacts:
    paths:
      - "out/cover.html"