before_script:
  - git config --global http.proxy "${HTTP_PROXY}"
  - git config --global https.proxy "${HTTPS_PROXY}"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
  - export http_proxy="${HTTP_PROXY}"
  - export https_proxy="${HTTPS_PROXY}"
  - export no_proxy="${NO_PROXY}"
  - env
  - git config --list

stages:
  - build
  - test

build:gta:
  stage: build
  image: tpm-devel
  tags:
    - tpm-devel
  script:
    - make
  artifacts:
    paths:
      - "out/tpmprovider.test"

test:
  stage: test
  image: tpm-devel
  tags:
    - tpm-devel
  script:
    - make unit_test
  artifacts:
    paths:
      - "out/cover.html"
