stages:
  - build
  - test

build:gta:
  stage: build
  image: gta-devel
  tags:
    - gta
  script:
    - make
  artifacts:
    paths:
      - "out/tpmprovider.test"
    expire_in: 1 week

test:
  stage: test
  image: gta-devel
  tags:
    - gta-unit-test
  script:
    - go test ./... -tags=unit_test -coverpkg=./... -coverprofile cover.out
    - go tool cover -func cover.out
    - go tool cover -html=cover.out -o cover.html
  artifacts:
    paths:
      - "cover.html"